// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_AngelGuerrero.DAL;

#nullable disable

namespace P1_AP1_AngelGuerrero.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251010005610_Mejoras")]
    partial class Mejoras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_AngelGuerrero.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_AP1_AngelGuerrero.Models.EntradasHuacalesDetalles", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoHuacalTipoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("TipoHuacalTipoId");

                    b.ToTable("EntradasHuacalesDetalles");
                });

            modelBuilder.Entity("P1_AP1_AngelGuerrero.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "RojoGrande",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "RojoMediano",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "VerdeGrande",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 4,
                            Descripcion = "VerdeMediano",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("P1_AP1_AngelGuerrero.Models.EntradasHuacalesDetalles", b =>
                {
                    b.HasOne("P1_AP1_AngelGuerrero.Models.EntradasHuacales", "EntradaHuacal")
                        .WithMany("EntradasHuacalesDetalles")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_AP1_AngelGuerrero.Models.TiposHuacales", "TipoHuacal")
                        .WithMany()
                        .HasForeignKey("TipoHuacalTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");

                    b.Navigation("TipoHuacal");
                });

            modelBuilder.Entity("P1_AP1_AngelGuerrero.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
